### ISSUE TITLE
Generate a static site from post files

### ISSUE THREAD

**Issue by johnjago** [johnjago/blognow#1]
A writer should be able to run the command `blognow` in the root directory of a blog to generate the static site in dist/ from a configuration file and all the post files in Markdown format in post/.

The front page will have the blog title, a tagline, the most recent post, and a link to see all posts. Post pages will have the same information.

**Tasks**
- [x] Create a template for the front page/single post page.
- [x] Create a template for the "all posts" page.
- [x] Add tagline support.
- [x] Generate a single post in HTML from the respective markdown file.
- [x] Generate the "all posts" page based on all titles and dates read in from each post file.
- [x] Create output in dist/. There will be an index.html (the most recent post) along with a directory for each post (directory title/slug comes from the post's title). Inside the directory will be an index.html file containing that post.

Below are some examples of what I'm thinking it will look like:

![Screenshot-2019-7-14 Matt](https://user-images.githubusercontent.com/19847480/61184510-2a417380-a614-11e9-814c-8f6655fcdf75.png)

![Screenshot-2019-7-14 zen habits](https://user-images.githubusercontent.com/19847480/61184514-375e6280-a614-11e9-9fd0-e41deb19b2eb.png)

---

![Screenshot-2019-6-28 inimino's blog](https://user-images.githubusercontent.com/19847480/60377295-1de5d580-99db-11e9-81cc-bba38240518c.png)
